# fly.toml file

app = "xxx"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  Api_hash = "xxx"
  Api_id = "xxx"
  Aria2_secret = "xxx"
  Remote = "xxx"
  Telegram_bot_api = "xxx"
  Telegram_user_id = "xxx"
  Upload = "xxx"
  Rclone_share = "False"
  Error_user_info = "你没有使用权限"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8868
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

