# This is a basic workflow to help you get started with Actions

name: Repo Issues Notify


on:
  issues:
    types: [opened, edited, milestoned]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Star Count
        id: repo-stars
        uses: alanhg/repo-star-count-action@master
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event.sender.login }} ${{ github.event.action }} ${{ github.event.repository.name }} 的 议题
            标题: ${{ github.event.issue.title }}
            内容: ${{ github.event.issue.body }}

            项目地址:https://github.com/${{github.repository}}
          

  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"

